### ISSUE TITLE
Pip install errors

### ISSUE THREAD

**Issue by AntonioDLC** [omseeth/AM_BERT_classification#1]
> The 'sklearn' PyPI package is deprecated, use 'scikit-learn' rather than 'sklearn' for pip commands.

I changed the module name in the requeriments.txt file and it seems be installing fine. Will add new errors if any come up.

**Comment by omseeth** [comment]
Thank you very much, @AntonioDLC! I changed the package name to 'scikit-learn'. Please, let me know if there are any other errors.
